// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbAIWh3BZEFPG9E7AN4IET4w-TQtuzCZg',
    appId: '1:973541461274:web:4b505f10f32b7ded49f0a3',
    messagingSenderId: '973541461274',
    projectId: 'e-commerce-99bba',
    authDomain: 'e-commerce-99bba.firebaseapp.com',
    storageBucket: 'e-commerce-99bba.appspot.com',
    measurementId: 'G-VMR0DD5T3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA783kWNFBGnKNWLfvkpAh7qwwN9rHQthg',
    appId: '1:973541461274:android:81cdf0dccd449a2c49f0a3',
    messagingSenderId: '973541461274',
    projectId: 'e-commerce-99bba',
    storageBucket: 'e-commerce-99bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1FlZ3M1qh0bYizXMBBAJ956qWEK9_boA',
    appId: '1:973541461274:ios:ed9562bff67cee1a49f0a3',
    messagingSenderId: '973541461274',
    projectId: 'e-commerce-99bba',
    storageBucket: 'e-commerce-99bba.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1FlZ3M1qh0bYizXMBBAJ956qWEK9_boA',
    appId: '1:973541461274:ios:ed9562bff67cee1a49f0a3',
    messagingSenderId: '973541461274',
    projectId: 'e-commerce-99bba',
    storageBucket: 'e-commerce-99bba.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbAIWh3BZEFPG9E7AN4IET4w-TQtuzCZg',
    appId: '1:973541461274:web:5f992419a5ba88fc49f0a3',
    messagingSenderId: '973541461274',
    projectId: 'e-commerce-99bba',
    authDomain: 'e-commerce-99bba.firebaseapp.com',
    storageBucket: 'e-commerce-99bba.appspot.com',
    measurementId: 'G-K955BERXCD',
  );
}
